server:
  port: 5000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Product Service
        - id: product-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/products/**

        # Cart Service
        - id: cart-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/cart/**

        # Order Service
        - id: order-service
          uri: http://localhost:9022
          predicates:
            - Path=/api/orders/**

        # Customer / Auth Service
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
