name: Build Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Images
      run: |
        docker compose build
        echo "✅ Docker images built successfully"

    - name: List Docker Images
      run: |
        docker images
